# Screen
SCREEN_WIDTH, SCREEN_HEIGHT = 1280, 720

# Laser
LASER_VECTOR_POS = (0, 1)
LASER_SPEED = 800
LASER_AUTODESTRUCTION_HEIGHT = 0

# Ship
SHOOT_COOLDOWN = 300

# Asteroid
ASTEROID_X_VECTOR_INTERVAL = (-0.5, 0.5)
ASTEROID_Y_VECTOR = 1
ASTEROID_SPEED_INTERVAL = (400, 600)
ASTEROID_COOLDOWN = 200
ASTEROID_START_XPOS_INTERVAL = (-100, SCREEN_WIDTH+100) 
ASTEROID_START_YPOS_INTERVAL = (-150, -50)
ASTEROID_AUTODESTRUCTION_HEIGHT = SCREEN_HEIGHT
ASTEROID_SIZE_INTERVAL = (0.5, 1.5)
ASTEROID_ROTATION_SPEED_INTERVAL = (20, 50)

# Score
SCORE_FONT_SIZE = 50
SCORE_COLOR = '#ffffff'
SCORE_POS = (SCREEN_WIDTH//2, 9*SCREEN_HEIGHT//10)
SCORE_BORDER_WIDTH = 8
SCORE_BORDER_INFLATE = (30, 30)
SCORE_BORDER_COLOR = (255,255,255)
SCORE_BORDER_RADIUS = 5
